#ifndef _IO_H_
#define _IO_H_

/* jtag */
#define GPIO_TDI        CONFIG_BRIDGE_GPIO_TDI
#define GPIO_TDO        CONFIG_BRIDGE_GPIO_TDO
#define GPIO_TCK        CONFIG_BRIDGE_GPIO_TCK
#define GPIO_TMS        CONFIG_BRIDGE_GPIO_TMS

/* serial */
#define GPIO_BOOT       CONFIG_BRIDGE_GPIO_BOOT
#define GPIO_RST        CONFIG_BRIDGE_GPIO_RST
#define GPIO_RXD        CONFIG_BRIDGE_GPIO_RXD
#define GPIO_TXD        CONFIG_BRIDGE_GPIO_TXD

/* leds */
#define LED_TX          CONFIG_BRIDGE_GPIO_LED1
#define LED_RX          CONFIG_BRIDGE_GPIO_LED2
#define LED_JTAG        CONFIG_BRIDGE_GPIO_LED3

#define LED_TX_ON       CONFIG_BRIDGE_GPIO_LED1_ACTIVE
#define LED_TX_OFF      (!CONFIG_BRIDGE_GPIO_LED1_ACTIVE)

#define LED_RX_ON       CONFIG_BRIDGE_GPIO_LED2_ACTIVE
#define LED_RX_OFF      (!CONFIG_BRIDGE_GPIO_LED2_ACTIVE)

#define LED_JTAG_ON     CONFIG_BRIDGE_GPIO_LED3_ACTIVE
#define LED_JTAG_OFF    (!CONFIG_BRIDGE_GPIO_LED3_ACTIVE)

#endif
