#ifndef _IO_H_
#define _IO_H_

/* jtag */
#define GPIO_TDI     CONFIG_BRIDGE_GPIO_TDI
#define GPIO_TDO     CONFIG_BRIDGE_GPIO_TDO
#define GPIO_TCK     CONFIG_BRIDGE_GPIO_TCK
#define GPIO_TMS     CONFIG_BRIDGE_GPIO_TMS

/* serial */
#define GPIO_BOOT    CONFIG_BRIDGE_GPIO_BOOT
#define GPIO_RST     CONFIG_BRIDGE_GPIO_RST
#define GPIO_RXD     CONFIG_BRIDGE_GPIO_RXD
#define GPIO_TXD     CONFIG_BRIDGE_GPIO_TXD



#endif
